// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbpxvccaefeizwaojxud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZicHh2Y2NhZWZlaXp3YW9qeHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NjQ4NDcsImV4cCI6MjA2MzA0MDg0N30.e-Nbv6pjUUVGzNwCKgCByD8UR6EWK0EWZ98GgmcCw3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);